/**
 * Take the given array of field errors generated by server validation and
 * reduce them to an object keyed by field name.
 *
 * @param {Array} errors - The array of generated field errors.
 * @return {Object} The object of errors keyed by field name.
 */
export default function(errors) {
  return errors.reduce((current, error) => Object.assign(current, error), {});
}
